# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301e899f8e9ba4a0ceea394915b48a2908b4e27e37ef60c2a492d3f552687bca1527cad56ce97cb7e98c3c76733ae6aa77344c1b2163ab6299222f0b9de98908

test:
  secret_key_base: 80af208dfd425e448d15dcd1518999559d38d045549924d9eb277379a51269f8bed67255d98815e5ab276c3bdc055dfe59b246b820274289259ff33c2ae5324f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
